//
//  ReflectimeV9App.swift
//  ReflectimeV9
//
//  Created by Ian Relecker on 10/29/22.
//  App Icon Generated by https://apps.apple.com/us/app/dream-by-wombo-ai-art-tool/id1586366816

import SwiftUI
import RevenueCat

@main
struct ReflectimeV9App: App {
    @StateObject private var dataController = DataController()
    
    var body: some Scene {
        WindowGroup {
            TabsView()
                .environment(\.managedObjectContext, dataController.container.viewContext)
        }
    }
    init() {
        
        
        
        //rev cat code
        //This code is adapted from https://www.revenuecat.com/docs/getting-started
        Purchases.logLevel = .debug
        Purchases.configure(withAPIKey: "appl_QlJQRSJGsQftOnEdMzVzhdUSQlq")
        let defaults = UserDefaults.standard
        Purchases.shared.restorePurchases { (customerInfo, error) in
            if customerInfo?.entitlements.all["Pro"]?.isActive == true {
                defaults.set(true, forKey: "pro")
            }else{
                defaults.set(false, forKey: "pro")
            }
        }
        //
    }
}
